name = "hammal"
account_id = "96f65b8ff00b56968826ae918be52995"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-06-08"

kv_namespaces = [
	 { binding = "hammal_cache", id = "6af42d117e92422587bce29f0674fe53" }
]
